language: groovy
jdk:
- oraclejdk8
env:
  global:
  - secure: EsdiolxbnGKAKwlwEp9UQppbpgEe+H4yCqlaLvxMBhMJtiYNXlWZ256nI3yPOUQBRTUYm5Wm2SqH+0QBUJKtderFuv4CLeada8kdMgcyptyqk5rI8j2HjEnt8fWd+FDBIvQvX0dumi+BIMoXoibgEcHi9rs6XD4m9t9hDxWkR8s=
  - secure: LTUWwsmnivxbGwlrsaVf0aSRoh7BzOfUfMBlJ1MGvsRCrk7B34pc36ZD1ACn/GWynqPZFz+FWjOhjDlP9ymfxzYxkBc5Cwpcw1KiknwCH3KQqZ8QC8m0tIF/rPdcRS25tf+9w8cnwdVbDDCxkvadFw8BF8VCbe+oZhps6O+2X/E=
  - secure: QL1HVvZqZ0C/2uUp+ZUPj9Xk/P5bgLwWiPPXFfz9lFCoTv7wiOjhgsJCSOoDU2KlBCS1J4bAwhEzi5xJ/hkCQ5ZN2NTXC8RXvmk645NukpbRMhIqw2ZVgETmUvX/xqY7m8UoZwPXEmyTf3Qjmmnr3pGmtTnYilKhxYF+zCJ9SSQ=
  - secure: QZqqh9xKLDfO5b6Is8xqgBQ5nbY3W3tl0abVLd0/BgrPSHFw6MVqeJ+Ymg+v2xeF8AIazEjYFpQTwg8tF/YVeI0elM4M2bCC9tl1JyRKeFdSzIHkVRk580HbCiR64BMFAz1gCrc1xZmLxTOTpRhcXxm1onU9T8wU2wSF2PIQoTc=
  - secure: Fjb7SLgAnPEAra/ZvPTxqU5wPuuvC/k0ve5Nmtom0cMhdGTjF/WM4ATuuU6PR9ThEKygADAdZ78DRrEzivXkcbjx1R85uFHwZ5LqnrQ3XOOgiPIalj8vHXPAtkV+lazHZxEQDZBNW0p+dEwheb4nA51fYB2AXYs5ndnKgSHBut4=
  - secure: Y51rT6822FAxunIkrPFDBcmMNXpxD3tZfeyxlSbuPXltU5dOysj1QIEXSVr5qXjKkjQ7mdHCI4NfkpNebyNqv90iJ/VxfrDveujlpxWjjrSKRpU3qQ7nOxnrSayCfq15Ox0YzIHi+Ff4PSy8gN6Ojfl8e7U8URCbFNmr3zozR9U=
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/b05b9117066dbe11bb14
    on_success: change
    on_failure: always
    on_start: false
branches:
  only:
  - develop
  - master
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ./gradlew
  bintrayUpload -Pbintray_net_user="${bintray_net_user}" -Pbintray_net_key="${bintray_net_key}" && ./gradlew publishPlugins -Dgradle.publish.key=${gradle_publish_key} -Dgradle.publish.secret=${gradle_publish_secret}
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "develop" && ./gradlew
  plugin:publishMavenPublicationToJcenterSnapshotRepository -Pbintray_net_user="${bintray_net_user}"
  -Pbintray_net_key="${bintray_net_key}"
